# Sample requests for the TODO service
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
# get all items
GET http://localhost:8080/items

###
# get item
GET http://localhost:8080/items/1

###
# create item
POST http://localhost:8080/items
Content-Type: application/json

{
    "subject": "another example",
    "done": false
}

###
# update item
PUT http://localhost:8080/items/1
Content-Type: application/json

{
    "subject": "first example",
    "done": true
}

###
# delete item
DELETE http://localhost:8080/items/1