name: Dockerize todo-service

on:
  push: # temp
    paths: # temp
      - "todo-service/**"

  workflow_run:
    workflows:
      - Build todo-service
    branches:
      - main
    types:
      - completed

  workflow_dispatch:

jobs:
  dockerize:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./todo-service
          file: ./todo-service/src/main/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: konphite/todo-service:latest
